Feature/2 サインアップ後の画面遷移 確認
minty1202/kensyu pull request #13
Opened 2022-05-09 10:03 UTC by kazufoot21

ご確認お願い致します。

2022-05-10 07:15 UTC, kazufoot21 commented
test

2022-05-10 07:30 UTC, kazufoot21 commented
@minty1202 
Rspec で例えば下記のように書いている部分を

```
      it 'ログイン状態であること' do
        post user_registration_path, params: user_params
        expect(response).to have_http_status(302)
      end
```


`expect(sign_in?).to be_truthy` のようにsign_in?で判断するにはどうすればよいのでしょうか？
`config.include Devise::Test::IntegrationHelpers, type: :request`を記述することでdeviseのヘルパーメソッドが使えると思ったのですが、できませんでした。

2022-05-10 08:46 UTC, minty1202 requested changes
せっかくslimに直してくださったものもあるのに申し訳ありません。

テストに関しては階層に分けましょう
```
request
|-user
   |-session
   |-registration_path
```

また正常系のみで構わないのでadminのテストもお願いします

2022-05-10 08:46 UTC, minty1202 commented on Gemfile
> +gem 'bootstrap-sass'
参考までに
画面関係はyarnを使うのが一般的です。
今回はこのままで大丈夫です。

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/application_controller.rb
> +  end
Users::RegistrationsController
に書いてください

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  end
protected
よりも下の行に書いてください

2022-05-10 08:46 UTC, minty1202 commented on db/migrate/20220509070757_add_name_to_users.rb
> +end
db/migrate/20220509063425_devise_create_users.rb
に追記しましょう。
また、null: falseもつけておきましょう

2022-05-10 08:46 UTC, minty1202 commented on spec/models/user_spec.rb
> +  let(:user) { User.new(name: 'Example User', email: 'user@example.com',password: "foobar", password_confirmation: "foobar") }
Factorybotをつかっているのであれば
build等で出来るのではないでしょうか？

2022-05-10 08:46 UTC, minty1202 commented on spec/models/user_spec.rb
> +    duplicate_user.email = user.email.upcase
複製した後に大文字のemailを挿入するのはいまいち理由がわからなかったです。
教えていただけると助かります

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/session_spec.rb
> +    end
このテスト通るのはおかしいです。
実際テスト response の中身を見てみましたがログインされたような風には見えませんでした。

違和感がある点としては
1. userが存在しないのにログインできている
2. ログインに必要な情報が入っていない

改めて見直していただけると助かります。

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/user_spec.rb
> +  end
```ruby
let(:user) { build(:user) }
```

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/user_spec.rb
> +        user = User.last
この記述は不要な気がします

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/user_spec.rb
> +        expect(response).to have_http_status(302)
これだとログイン状態かどうかではなくリダイレクトしたかどうかになると思います。
例えばsession id を持ってるかどうかでログイン状態を確かめたりするといいと思います
```ruby
expect(!!session.id).to be_truthy
```

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/session_spec.rb
> +      expect(response).to have_http_status(204)
セッションの有無等で確かめられるといいと思います

2022-05-10 08:46 UTC, minty1202 commented on spec/models/user_spec.rb
> +end
正常系のテストがあるとよいです。
```ruby
it { expect(user).to be_valid
```

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/user_spec.rb
> +        user = User.last
```ruby
describe 'POST /users/registrations#create' do
  context '無効な値の場合' do
    it ...
  end

  context '有効な値の場合' do
    it ...
  end
```

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/admins/passwords_controller.rb
> +# frozen_string_literal: true
今回なファイルですので消してください

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/admins/unlocks_controller.rb
> +# frozen_string_literal: true
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/users/passwords_controller.rb
> +# frozen_string_literal: true
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/controllers/users/unlocks_controller.rb
> +# frozen_string_literal: true
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/mailer/password_change.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/mailer/reset_password_instructions.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/mailer/unlock_instructions.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/passwords/edit.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/passwords/new.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/admins/unlocks/new.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/mailer/password_change.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/mailer/reset_password_instructions.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/mailer/unlock_instructions.html.slim
> +p
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/passwords/edit.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/passwords/new.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on app/views/users/unlocks/new.html.slim
> +h2
ditto

2022-05-10 08:46 UTC, minty1202 commented on spec/requests/user_spec.rb
> +require 'rails_helper'
ファイル名は
registration
のほうがよいでしょう

2022-05-10 08:49 UTC, minty1202 commented
> @minty1202 Rspecでされてのようにます
> 
> ```
>       it 'ログイン状態であること' do
>         post user_registration_path, params: user_params
>         expect(response).to have_http_status(302)
>       end
> ```
> 
> `expect(sign_in?).to be_truthy`のようにsign_in `config.include Devise::Test::IntegrationHelpers, type: :request`？

sign_in?で判断する方法がわからなかったため代案を書いておきました。
遅くなりすみません

2022-05-10 09:23 UTC, kazufoot21 commented on db/migrate/20220509070757_add_name_to_users.rb
> +end
@minty1202 
あとからカラムを追加するときは20220509070757_add_name_to_users.rbを作らずにdb/migrate/20220509063425_devise_create_users.rbに追記するということでしょうか？

2022-05-10 09:32 UTC, kazufoot21 commented on spec/models/user_spec.rb
> +    duplicate_user.email = user.email.upcase
@minty1202 
特に理由はないです。勘違いしていました。

2022-05-11 02:24 UTC, minty1202 commented on spec/requests/user_spec.rb
> +        expect(response).to have_http_status(302)
```ruby
!!session.id
```
よりも
```ruby
session.id.present
```
のほうがわかりやすいかも

2022-05-11 03:07 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  # end
ここ読んでみてください

2022-05-11 03:07 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
```ruby
before_action :configure_permitted_parameters, if: :devise_controller?
```
これはdeviseのコントローラを拡張しないときに書く記述なので不要です

2022-05-11 03:07 UTC, minty1202 commented on app/views/users/shared/_links.html.slim
> +- if controller_name != 'sessions'
消したページのリンクも消してもらえると助かります

2022-05-11 03:07 UTC, minty1202 commented on spec/models/admin_spec.rb
> +  let(:user) {build(:user) }
admin用のfactory_botを作成してください

2022-05-11 03:07 UTC, minty1202 commented on spec/models/admin_spec.rb
> +  end
正常系のテストがあるとよいです。
```ruby
it { expect(admin).to be_valid }
```

2022-05-11 03:07 UTC, minty1202 commented on spec/requests/user/session_spec.rb
> +    it "return http success" do
let!(:user) { build(:user) }

2022-05-11 03:07 UTC, minty1202 commented on spec/models/user_spec.rb
> +    duplicate_user.email = user.email
email事態は同一のはずなのでわざわざ明示させる必要もない気がします

2022-05-11 03:07 UTC, minty1202 commented on db/migrate/20220509070757_add_name_to_users.rb
> +class AddNameToUsers < ActiveRecord::Migration[7.0]
このファイルいらないです

2022-05-11 03:19 UTC, minty1202 commented
> let(:user) { build(:user) }で作成したものを使ってドライに書きたいのですが、 下記を書き換えるにはどのように書けばよいのでしょうか？
> 
> `post user_registration_path, params: { user: { name: 'test', email: 'test@example.com', password: '123456', password_confirmation: '123456' }`

```ruby
post user_registration_path, params: user
```
で行けると思います

2022-05-11 03:25 UTC, kazufoot21 commented on spec/requests/user/session_spec.rb
> +    it "return http success" do
> let!(:user) { build(:user) }

これは一番上に書くという意味でしょうか？

2022-05-11 04:05 UTC, kazufoot21 commented
> テスト

2022-05-11 04:07 UTC, kazufoot21 commented
> > let(:user) { build(:user) }で作成したものを使ってドライに書きたいのですが、 下記を書き換えるにはどのように書けばよいのでしょうか？
> > `post user_registration_path, params: { user: { name: 'test', email: 'test@example.com', password: '123456', password_confirmation: '123456' }`
> 
> ```ruby
> post user_registration_path, params: user
> ```
> 
> で行けると思います

事前に同じ形でやってみましたが、できませんでした。

2022-05-11 04:08 UTC, kazufoot21 commented on app/controllers/users/registrations_controller.rb
> +  # end
確認中

2022-05-11 04:08 UTC, kazufoot21 commented on spec/models/admin_spec.rb
> +  let(:user) {build(:user) }
確認中

2022-05-11 04:08 UTC, kazufoot21 commented on spec/models/admin_spec.rb
> +  end
確認中

2022-05-11 04:11 UTC, minty1202 commented on spec/requests/user/session_spec.rb
> +    it "return http success" do
そうです。

2022-05-11 04:12 UTC, minty1202 commented
> ```ruby
> ```ruby
> registration_path, params: user
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> で行けると思います
> 
> 事前に同じ形でやってみましたが、できませんでした。
> ```

確認してみますね

2022-05-11 04:40 UTC, minty1202 commented
```ruby
params: {user: user.attributes} 
```
で行けるかと思ったら無理でしたね
失礼しました。
DRYで書くとしたら
```ruby
let(:user_params) {  { user: { name: 'test', email: 'test@example.com', password: '123456', password_confirmation: '123456' } } }
```
で先に定義するのが限界な気がします

2022-05-11 08:29 UTC, minty1202 commented on spec/requests/user/session_spec.rb
> +      expect(!!session[:user_id]).to_not be_truthy
deviseではログアウトした後もセッション情報がある程度の期間保持されるのでsessionで判断は無理そうでした
ログアウトのテストでは
expect(!!session[:user_id]).to_not be_truthy
この記述はなくていいです

2022-05-11 08:29 UTC, minty1202 commented on spec/requests/user/session_spec.rb
> +    it "return http success" do
let!(:user) { build(:user) }
ではなく
let!(:user) { create(:user) }
でした。申し訳ありません。

後リダイレクトされるはずなので have_http_status :success
ではなくなります

2022-05-11 08:29 UTC, minty1202 commented on spec/requests/admin/session_spec.rb
> +      expect(response).to have_http_status :success
これが通るのはおかしいです。

2022-05-11 08:29 UTC, minty1202 commented on spec/requests/admin/session_spec.rb
> +      expect(!!session[:user_id]).to_not be_truthy
expect(!!session[:user_id]).to_not be_truthy
これは消しといてください

2022-05-11 08:29 UTC, minty1202 commented on spec/models/user_spec.rb
> +  it 'すべての値が通る' do
すべての値が正常であれば登録できる

2022-05-11 08:29 UTC, minty1202 commented on config/routes.rb
> +  end
よくよく思ったんですけどこの記述いりますか？

2022-05-11 08:34 UTC, kazufoot21 commented on config/routes.rb
> +  end
sign_putのルーティングエラーがおきたので、こちらを記述しました。

2022-05-11 09:46 UTC, minty1202 commented on config/routes.rb
> +  end
たぶんブートストだとhttpmethodのput delete が機能しない問題だと思います。
どちらにせよ後々対応しないとですね

2022-05-11 09:47 UTC, minty1202 approved these changes
LGTM です
マージして次に進んでください

2022-05-11 09:52 UTC, kazufoot21 commented on config/routes.rb
> +  end
承知しました。

2022-05-11 09:53 UTC, merged