[add]#4 mypageの実装
minty1202/kensyu pull request #18
Opened 2022-05-12 07:10 UTC by kazufoot21

### Why
マイページでユーザー情報とTodoリストを確認するため

### What
・マイページにユーザー情報とTodoリスト表示
・リクエストテスト

2022-05-12 07:48 UTC, minty1202 requested changes
画像ももらえると助かります。

2022-05-12 07:48 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +      mypage_path(current_user)
mypage_path(resource)

2022-05-12 07:48 UTC, minty1202 commented on app/controllers/users/sessions_controller.rb
> +      mypage_path(current_user)
ditto

2022-05-12 07:48 UTC, minty1202 commented on app/views/mypage/show.html.slim
> +    li.user= @user.name
`@user`をわざわざ使わなくても`current_user`で事足りると思います。

2022-05-12 07:48 UTC, minty1202 commented on app/views/mypage/show.html.slim
> +  - unless @todos.empty?
`current_user.todos`

2022-05-12 07:48 UTC, minty1202 commented on app/controllers/mypage_controller.rb
> +  end
def show; end

2022-05-12 07:48 UTC, minty1202 commented on spec/requests/mypage_spec.rb
> +      expect(response).to have_http_status(:success)
これが通るならログインいらないですね。

2022-05-12 07:48 UTC, minty1202 commented on app/controllers/mypage_controller.rb
> +class MypageController < ApplicationController
多分url指定したら誰でもはいれるんじゃないでしょうか

2022-05-12 07:48 UTC, minty1202 commented on config/routes.rb
> +  resources :mypage
namespaceを使えるとよいです。
また onlyも使いましょう
indexを作ることはないと思うのでresoure

2022-05-12 07:50 UTC, minty1202 commented
git merge develop
をしていただけると助かります

2022-05-13 04:13 UTC, minty1202 requested changes

2022-05-13 04:13 UTC, minty1202 commented on app/controllers/users/mypages_controller.rb
> +class Users::MypagesController < ApplicationController
userscontrollerを継承してください

2022-05-13 04:13 UTC, minty1202 commented on app/controllers/users_controller.rb
> +  # before_action :authenticate_user!
コメントアウト外してください
また、path的にUsers::Userscontrollerではないと思います
Users:: は usersディレクトリを表します。
今回はapp/controller/users_controllerなので
UsersController < Applicationcontroller
で問題ないかと

2022-05-13 04:13 UTC, minty1202 commented on app/views/users/mypages/show.html.slim
> +div
slimはdivを省略します

2022-05-13 04:13 UTC, minty1202 commented on config/puma.rb
> +port ENV.fetch("PORT") { 3001 }
port変える必要ありました？
帰るならdocker-composeでかえたいです。

2022-05-13 04:13 UTC, minty1202 commented on config/routes.rb
> +    resource :mypage, only:[:show]
一つだけなら
only: :show

2022-05-13 04:13 UTC, minty1202 commented on spec/requests/user/mypage_spec.rb
> +  end
```ruby
describe "GET /mypage #show" do
    context 'ログインしている場合' do
      before do
        sign_in(user)
      end
      it "returns http success" do
        get users_mypage_path(user)
        expect(response).to have_http_status(:success)
      end
    end
    context 'ログインしていない場合' do
      # ...
    end
end
```

2022-05-13 04:13 UTC, minty1202 commented on app/views/users/mypages/show.html.slim
> +  - else
早期リターン等特別な理由がなければunlessは極力避けるようにしましょう

if current_user.todos.present?

2022-05-13 09:01 UTC, kazufoot21 commented on app/controllers/users_controller.rb
> +class Users::UsersController < ApplicationController
ここに共通の処理を書きたい？と思ったのですが、反映されないので書き方が間違っている箇所を教えて頂きたいです。

2022-05-13 09:41 UTC, minty1202 approved these changes
![LGTM](https://image.lgtmoon.dev/155758)

2022-05-13 10:24 UTC, merged