Fature/8 9 11
minty1202/kensyu pull request #24
Opened 2022-05-23 09:33 UTC by kazufoot21

Fature/8 9 11 同じブランチに実装しています。(現在issue8, 9)

#WHAT
issue8 rootページですべてのTodoを確認
issue9 コメント機能実装
issue11 

#WHY
issue8 
rootページでtodoを確認
todoをクリックした際に詳細（編集）ページに遷移
ログインしていない場合はログイン画面に遷移
リクエストテスト
<img width="1738" alt="スクリーンショット 2022-05-23 18 29 54" src="https://user-images.githubusercontent.com/73515602/169789588-d89b964a-d498-45b5-8a64-3ad3f51712aa.png">

issue9  
commentモデルの作成
詳細（編集）ページでコメント表示
コメントを閲覧できるよ
各アソシエーションをつける
単体テスト
リクエストテスト
<img width="1421" alt="スクリーンショット 2022-05-23 18 30 23" src="https://user-images.githubusercontent.com/73515602/169789628-f0e9dee6-55c3-40d5-850a-7c5ab36b3b10.png">

<img width="1245" alt="スクリーンショット 2022-05-23 18 30 48" src="https://user-images.githubusercontent.com/73515602/169789623-c05a94c3-7845-4e5c-a9d7-63ec799294ad.png">

issue11

2022-05-23 10:00 UTC, minty1202 requested changes
test 落ちてます。
ご確認お願いします。

2022-05-23 10:00 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +      redirect_to edit_users_todo(@todo)
```
redirect_to edit_users_todo(@comment.todo)
```

2022-05-23 10:00 UTC, minty1202 commented on app/controllers/general_controller.rb
> +    @todos = Todo.all
たぶん n + 1 起きてる

2022-05-23 10:00 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    @comment = current_user.comments.new
```
@comment = Commet.new(todo_id: @todo.id, user_id: current_user.id)

2022-05-23 10:00 UTC, minty1202 commented on app/models/todo.rb
> +  has_many :comments, dependent: :destroy
through オプションがあったほうがいい

2022-05-23 10:00 UTC, minty1202 commented on app/models/user.rb
> +  has_many :comments
ditto

2022-05-23 10:00 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    @comment = current_user.comments.new
多分 n + 1 起きてんじゃない？

2022-05-23 10:00 UTC, minty1202 commented on app/views/general/index.html.slim
> +    p.todos-info Todoがありません！
if で入れ子になるのは可能な限り避けてた方がいいでしょう。
例えばこんな書き方はどうでしょう？できるかどうかはわかりませんが。
```ruby
    - @todos&.each do |todo|
      - if todo.user === current_user
        = link_to edit_users_todo_path(todo)
          ul.todos-info-self
            li.user= todo.title
            li.user= todo.text
            li.user= todo.created_at
      - else
          ul.todos-info
            li.user= todo.title
            li.user= todo.text
            li.user= todo.created_at

    - if @todos.nil?
       p.todos-info Todoがありません！

2022-05-23 10:00 UTC, minty1202 commented on config/routes.rb
> +    resources :adminspage , only: [:index, :destroy]
これだとパスが
`admin/adominspages`
等になるので違和感があります。
ダッシュボード等を使いましょう。

2022-05-23 10:00 UTC, minty1202 commented on config/routes.rb
> +  end
これはすでに実装しているのでしょうか？
見当たらないのですが。

2022-05-23 10:00 UTC, minty1202 commented on db/migrate/20220522230301_create_comments.rb
> +      t.string :comment_text
こうするとインスタンスのテキストが
```ruby
@commet = Commet.new
@commet.commet_text
```
となるので違和感があります。
フツーにtextでいいと思います。

後、空白を許容しないようにしてください。

2022-05-24 09:29 UTC, kazufoot21 commented on spec/requests/user/todos_spec.rb
> +      # end
@minty1202 
ここの部分でテストが失敗していまいます。
原因がわからないのですがtodoコントローラーのeditアクションの部分が@commentで引っかかっている感じがするのですがどうでしょう？

エラー

`Failure/Error: = form_with model:[:users, @todo, @comment], method: :post do |f|

     ActionView::Template::Error:
       undefined method `model_name' for nil:NilClass
     
             convert_to_model(record_or_class).model_name`

2022-05-24 09:44 UTC, minty1202 requested changes

2022-05-24 09:44 UTC, minty1202 commented on config/routes.rb
> +    resources :dashbord , only: [:show, :destroy]
resource

2022-05-24 09:44 UTC, minty1202 commented on app/controllers/admins/dashbord_controller.rb
> +    @users = User.all
n + 1

2022-05-24 09:44 UTC, minty1202 commented on app/controllers/admins/dashbord_controller.rb
> +  before_action :authenticate_admin!
admin も同じ要領で admin controller作ってください

2022-05-24 09:44 UTC, minty1202 commented on app/controllers/admins/dashbord_controller.rb
> +    pp params
いらない表記消してください

2022-05-24 09:44 UTC, minty1202 commented on app/controllers/admins/sessions_controller.rb
> +      root_path(resource)
root_path なら resourceいらないのでは？

2022-05-24 09:44 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
>      @comments = @todo.comments
これって今更思ったけど、@todo.commentsでいいのでは？

2022-05-24 09:44 UTC, minty1202 commented on app/views/admins/dashbord/show.html.slim
> +  = link_to 'Logout', destroy_admin_session_path, method: :delete
ここのdelete機能してない。
多分getで送られてる
botton_to にすればreoutesで定義する必要がなくなると思います。

2022-05-24 09:44 UTC, minty1202 commented on app/views/layouts/application.html.slim
> +  body.wrapper
bodyにクラス名つけるのはあまりいいとは思えないです。
```html
<body class="wrapper">

</body>
```
って違和感ありません？

2022-05-24 09:44 UTC, minty1202 commented on config/routes.rb
> +    get '/admins/sign_out' => 'devise/sessions#destroy'
button_toにすればこれいらない

2022-05-24 09:44 UTC, minty1202 commented on db/migrate/20220522230301_create_comments.rb
> +      t.string :text
空白を許容しないでください。

2022-05-25 00:59 UTC, kazufoot21 commented on config/routes.rb
> +    resources :dashbord , only: [:show, :destroy]
@minty1202 
resourceにするとadminの区別ができなくないですか？

2022-05-25 01:21 UTC, minty1202 commented on spec/requests/user/todos_spec.rb
> +      # end
@commentが作られていない状態でrenderしてるからエラーになってる。
一度editページ経由してからならエラー起きないと思います。

2022-05-25 01:24 UTC, minty1202 commented on config/routes.rb
> +    resources :dashbord , only: [:show, :destroy]
dashbordがadminにとって複数存在するかどうかがresourcesとresourceの違いになります。
dashbord自体はとくに複数個扱わないと思うのですがいかがでしょうか？

2022-05-25 01:24 UTC, minty1202 commented on spec/requests/user/todos_spec.rb
> +      # end
@kazufoot21

2022-05-25 03:31 UTC, kazufoot21 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
pp paramsの値を確認したところformat=1になってしまい、userIDがparamsに渡って来ないのですが、
viewでadmins_dashbord_path(user)のようにかいても削除したいuserのidが渡ってこないですよね？

| #<ActionController::Parameters {"_method"=>"delete", "authenticity_token"=>"hqSvsGGStGaoB7Hhg5CTI1KaGJMmmxT-oV_U9w2Q8StlO26Jz9Ebehps-3oas-c4BXWRkK0e_W1xMq6rhc95eQ", "controller"=>"admins/dashbords", "action"=>"destroy", "format"=>"1"} permitted: false>

2022-05-25 03:35 UTC, kazufoot21 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
resourcesからresouceに変えるからidパスが使えなくなるからですかね？

2022-05-25 03:40 UTC, kazufoot21 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
度々すみません。formatの値を渡せば削除できそうでした。

2022-05-25 03:45 UTC, minty1202 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
delete自体がdashbordを消す動きなので
adminsにuser_controllerを作成してください。
routesに
```ruby
  namespace :admins do
    resource :dashbord , only: [:show, :destroy]
    resources :users, only: [:index, :destroy]
  end
```

```slim
.todo-list
  - if @users.present?
    - @users.each do |user|
        ul.todos-info
          li.user ID:#{user.id}
          li.user 名前:#{user.name}
          li.user 投稿数：#{user.todos.count}
          li.user= button_to "削除する",admins_dashbord_path(user) , method: :delete
```

ここの部分はrenderで表示
削除の部分のパスはadmin_user に合わせしてください

2022-05-25 04:44 UTC, kazufoot21 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
@minty1202 
ありがとうございます。2点質問があります。
 resources :users, only: [:index, :destroy]でindexをなぜつくるのでしょうか？
現状部分テンプレートを使って表示させてるのですが、renderで表示というのはindexアクションで表示させるということでしょうか？

2022-05-25 04:48 UTC, minty1202 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
https://railsguides.jp/layouts_and_rendering.html
>resources :users, only: [:index, :destroy]でindexをなぜつくるのでしょうか？

user一覧を表示させたいからです。

現状部分テンプレートを使って表示させてるのですが、renderで表示というのはindexアクションで表示させるということでしょうか？

https://railsguides.jp/layouts_and_rendering.html#%E5%88%A5%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%8B%E3%82%89%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B

view の中で使います

2022-05-25 05:48 UTC, kazufoot21 commented on app/controllers/admins/dashbords_controller.rb
> +  def destroy
ありがとうございます。

2022-05-25 06:26 UTC, minty1202 approved these changes

2022-05-25 06:29 UTC, merged