Feature/12
minty1202/kensyu pull request #28
Opened 2022-05-26 08:54 UTC by kazufoot21

# Why
特定のTodo、Userを検索できるようにするため

# What
UserとTodoを検索できるようにする
検索後は、検索結果一覧ページを表示
リクエストテスト記述
<img width="1196" alt="スクリーンショット 2022-05-26 17 05 42" src="https://user-images.githubusercontent.com/73515602/170454456-4808ba6b-2885-4400-b865-25daa54930cc.png">

<img width="1363" alt="スクリーンショット 2022-05-26 17 04 29" src="https://user-images.githubusercontent.com/73515602/170454438-a61cbaea-f403-459f-acc2-566f26f3bc95.png">
<img width="1344" alt="スクリーンショット 2022-05-26 17 04 58" src="https://user-images.githubusercontent.com/73515602/170454450-fb450bf1-9ee9-4852-bc55-20000f5a7933.png">

2022-05-26 09:29 UTC, minty1202 requested changes

2022-05-26 09:29 UTC, minty1202 commented on app/models/todo.rb
> +          @todo = Todo.includes(:user).where("title LIKE ?", "#{word}")
Todo
いらない

2022-05-26 09:29 UTC, minty1202 commented on app/models/todo.rb
> +  end
ここの処理ほとんど同じだからmixinで行けるはず

2022-05-26 09:29 UTC, minty1202 commented on spec/requests/user/searches_spec.rb
> +RSpec.describe "Users::Searches", type: :request do
モデルのテストも書いてください。
リクエストテストはそれぞれの条件で想定する値が返ってきているか調べるまでしてください

2022-05-26 09:29 UTC, minty1202 commented on app/views/layouts/_search.html.slim
> +    = form_with url: users_search_path, local: true, method: :get do |f|
method: :get
いらない

というか post であるべき

2022-05-26 10:13 UTC, minty1202 commented on app/views/layouts/_search.html.slim
> +    = form_with url: users_search_path, local: true, method: :get do |f|
検索結果を取得するという意味では
get で問題のか。
すみません。postにしなくていいです。

2022-05-26 10:17 UTC, kazufoot21 commented on app/views/layouts/_search.html.slim
> +    = form_with url: users_search_path, local: true, method: :get do |f|
結局ログインしないとみれないのでgetでも意味ないかもと思いました...

2022-05-27 02:26 UTC, kazufoot21 commented on app/models/todo.rb
> +  end
@minty1202 

mixinについて学んだのですが、ここの部分でどのようにmixinを使うのかイメージ出来なかったので少しヒントなどを教えていただけますか？

2022-05-27 02:52 UTC, minty1202 commented on app/models/todo.rb
> +  end
https://railsguides.jp/getting_started.html#concern%E3%82%92%E4%BD%BF%E3%81%86
これ

2022-05-27 03:09 UTC, minty1202 requested changes

2022-05-27 03:09 UTC, minty1202 commented on app/views/layouts/_search.html.slim
> +    = form_with url: users_search_path, local: true, method: :get do |f|
form with はデフォが method: :getだったはずなんで省略可能です。
method: :get
いらない
はそう伝えたかったんですが、雑すぎましたね。すみません

2022-05-27 03:09 UTC, minty1202 commented on spec/models/user_spec.rb
> +  let(:user2) {create(:user, name: 'user2') }
遅延評価されちゃうので今回は
let!のほうが適当な気がします

2022-05-27 03:09 UTC, minty1202 commented on spec/models/todo_spec.rb
> +  let(:todo2) {create(:todo, title: 'todo2') }
diito

2022-05-27 03:09 UTC, minty1202 commented on spec/requests/user/searches_spec.rb
> +          expect(response.body).to include('perfect_match')
この場合 perfect_match の文字列を含んでいるか？
になるので恐らく検索欄の文字列にヒットしてるだけな気がします。

2022-05-27 03:10 UTC, minty1202 commented on app/models/todo.rb
> +  end
まぁ、無理そうならやらなくてもだいじょうぶです

2022-05-27 03:15 UTC, kazufoot21 commented on app/models/todo.rb
> +  end
ありがとうございます。

2022-05-27 03:53 UTC, kazufoot21 commented on spec/requests/user/searches_spec.rb
> +          expect(response.body).to include('perfect_match')
@minty1202 
検索結果ページのhiddenで隠している文字で判定するつもりで書いたのですが違いますか？

2022-05-27 04:15 UTC, kazufoot21 commented on app/models/todo.rb
> +  end
concern内でdef lookfor()..を共通化すると思うのですが、TodoやUserなど共通化しない部分を引数にして渡すところでちょっと行き詰まっています。先に修正箇所をpushします。

2022-05-27 04:32 UTC, minty1202 commented on spec/requests/user/searches_spec.rb
> +          expect(response.body).to include('perfect_match')
そもそものテスト要件に食い違いがありそうですね。
私はこのリクエストテストは
`適当なリクエストを送ると該当するインスタンスが検索され、画面に表示されること`
を保証するテスト内容であるべきだと思っていました。

前田さんとしてはどのような要件を満たすべきだと思い、テストを書かれましたか？
'完全一致の場合' では具体的に保障したいことが読み取れなかったので教えていただけると助かります。

2022-05-27 04:33 UTC, minty1202 commented on app/models/todo.rb
> +  end
そもそもクラス名は書かなくても動くはず。
もし動かないならselfでいいのでは？

2022-05-27 04:40 UTC, minty1202 reviewed
ページネーションは問題なさそうです

2022-05-27 04:40 UTC, minty1202 commented on Gemfile
> +gem 'kaminari'
ページネーションのレビューもしてしまっていいのでしょうか？
それならブランチを分けて別PRにするかPRに書き足してもらえると助かります。

2022-05-27 05:11 UTC, kazufoot21 commented on spec/requests/user/searches_spec.rb
> +          expect(response.body).to include('perfect_match')
受け取ったsearch paramsの値が検索結果ページで確認できることを保証できればいいと思っていました。
完全一致の場合の場合、perfect_matchが送らてくるので、該当のTodoが０の場合でも上記の場合で対応出来るものだと考えていました..

2022-05-27 05:15 UTC, kazufoot21 commented on Gemfile
> +gem 'kaminari'
承知しました。feature/13でPRします。

2022-05-27 05:23 UTC, minty1202 commented on spec/requests/user/searches_spec.rb
> +          expect(response.body).to include('perfect_match')
かしこまりましたそういうことであればそのままで大丈夫です。

2022-05-27 05:25 UTC, minty1202 approved these changes
一旦Approveします。
mixinを行うかどうかは任せます。

2022-05-27 07:08 UTC, merged