[upaate]#17 タグ機能
minty1202/kensyu pull request #34
Opened 2022-05-30 03:05 UTC by kazufoot21

# why
Todoに対してタグをつける

#What
User側がTodoに対して複数のタグを作れるようにする
Todo作成時にタグを付けれるようにする
編集ができるようにする
mypageにタグの一覧を表示、リンクでタグごとのページに飛べるようにする

2022-05-30 03:17 UTC, kazufoot21 commented on app/models/todo.rb
> +    puts current_tags
送られてきたタグの値を保存したいのですが、self.tagsで中身が確認できません。
中身がないので最終的に
`self.todo_tags << new_todo_tag`の部分でエラーになってしまいます。

【試したこと】
todoのコントローラでparamsの中身は確認→タグの値も送られてきている。
アソシエーションの確認
todo_paramsの変更
`   def todo_params
      params.require(:todo).permit(:title, :text, images: [], name: []).merge(user_id: current_user.id)
    end`

以上について考えて見ましたがわかりませんでした。
そのほかに考えられる原因がありましたら、ご教授お願いします。

2022-05-30 03:57 UTC, minty1202 commented on app/models/todo.rb
> +    puts current_tags
self.tags は TODO.tagsと同義なので値は取得できないと思います。

コントローラで
tags = TODO.tags
としても値が取れないのと同じ原理です。

アソシエーションはインスタンスを作らないと取得できないと思います。

2022-05-30 04:13 UTC, kazufoot21 commented on app/models/todo.rb
> +    puts current_tags
ありがとうございます。考え直してみます。

2022-05-30 04:23 UTC, minty1202 commented on app/models/tag.rb
> +  has_many :todos, through: :todo_tags
foreign_key: 'tag_id'
ってわざわざ設定しなくてもいい気がするけど、どんなんだろ？
後これって空白のバリデーションひつようなんじゃない？

2022-05-30 04:23 UTC, minty1202 commented on app/controllers/users/mypages_controller.rb
> +      @tags = Tag.includes(:todos) #ビューでタグ一覧を表示するために全取得。
これだと他人のタグも表示されない？

2022-05-30 04:23 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      tags = params[:todo][:name].split(',') # 送らててきたタグの取得
そもそも配列で来ないっけ？

2022-05-30 05:01 UTC, minty1202 commented
前田さんのやりたいことをしようと思ったらuserとtagにもアソシエーションいると思う。
ER図の時点で気づけなくて申し訳ない

2022-05-30 05:22 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      tags = params[:todo][:name].split(',') # 送らててきたタグの取得
配列で来ていないですね。

`app_1  | ---------params----------------
app_1  | {"authenticity_token"=>"xhYh_UP2lOhhoE_XN4Uw3u0_2IT8VLhNbD347q4JLuP6WS_ZNgFZ9fAM4nDzSmVtPJkDc-iFcq2depABjSRofA", "todo"=>{"title"=>"e", "text"=>"e", "name"=>"em, n", "images"=>[""]}, "commit"=>"登録する", "controller"=>"users/todos", "action"=>"create"}
app_1  | em, n`

2022-05-30 05:23 UTC, kazufoot21 commented on app/controllers/users/mypages_controller.rb
> +      @tags = Tag.includes(:todos) #ビューでタグ一覧を表示するために全取得。
おっしゃるとおりですね...

2022-05-30 05:25 UTC, kazufoot21 commented
> 

なるほどです。もう一度ER図から考えてみます。

2022-05-30 09:15 UTC, minty1202 commented on app/models/todo.rb
> +    puts current_tags
コントローラで
tags = TODO.tags
としても値が取れないのと同じ原理です。

ここ間違ったこと教えてました。すみません。使えると思います

2022-05-30 09:43 UTC, kazufoot21 commented on app/models/todo.rb
> +    puts current_tags
ありがとうございます！

2022-05-31 02:51 UTC, kazufoot21 commented
@minty1202 
まだテスト等がかけていませんが、進捗の確認のためpushしましたのでご確認お願いいたします。

未完成部分
form_withにおいて更新するとき、todoがもっているtagをvalueとして表示させる
テスト

2022-05-31 04:40 UTC, minty1202 commented on app/models/todo.rb
> +    end
これ処理ダブってない？

2022-05-31 04:40 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      tags = params[:todo][:name].split(',') # 送らててきたタグの取得, tagsは配列
tags = params[:todo][:name].split(',')
この書き方何度か使うならprivateメソッドかヘルパーメソッドにしたほうがいいとおもいます

2022-05-31 04:40 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +        end
やりたいことはわかるけど、これ編集時に正常にタグ来なかったら消えると思います。

2022-05-31 09:46 UTC, minty1202 requested changes

2022-05-31 09:46 UTC, minty1202 commented on app/models/tag.rb
> +  # end
これ使わないなら消してください

2022-05-31 09:46 UTC, minty1202 commented on app/views/users/todos/_form.html.slim
> +  - tags_name = @todo.tags.map(&:name)
pluck
に変えておいてください

2022-05-31 09:46 UTC, minty1202 commented on app/models/todo_tag.rb
> +  # end
これも

2022-05-31 09:46 UTC, minty1202 commented on db/migrate/20220527083604_create_tags.rb
> +      t.string :name
バリデーションつけるならここにも制約をつけてください

2022-05-31 09:46 UTC, minty1202 commented on spec/models/todo_spec.rb
> +    expect(tag).to_not be_valid
書かれているコードと it の内容がちぐはぐ

2022-05-31 09:46 UTC, minty1202 commented on spec/models/todo_spec.rb
> +  end
これは todoに書くべき内容なのだろうか？
またこれもちぐはぐ

2022-05-31 09:46 UTC, minty1202 commented on spec/models/todo_spec.rb
> +                                  name: tag2.name} } }
これ使うの？

2022-05-31 09:46 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag.name.split(',') - tag2.name.split(','))}.to_not change(Tag, :count)
tag2.name.split
ってそもそも配列じゃない

2022-05-31 09:46 UTC, minty1202 commented on spec/models/todo_spec.rb
> +                            name: tag3.name} } }
これ使って無くない？

2022-05-31 09:46 UTC, minty1202 commented on spec/requests/user/tag_spec.rb
> +        expect(response).to have_http_status(:success)
慣れてきたと思うので
例えば、タグの一覧が確認できるとか
そういうテストもできるといいですね。

2022-05-31 10:01 UTC, kazufoot21 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag.name.split(',') - tag2.name.split(','))}.to_not change(Tag, :count)
@minty1202 
splitメソッドって配列返さないですか？

2022-06-01 01:56 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag.name.split(',') - tag2.name.split(','))}.to_not change(Tag, :count)
@kazufoot21 
文字列の中に , がなくても配列返すんですね。
すみません間違えました

2022-06-01 07:18 UTC, minty1202 approved these changes
let と let! の違いをあまりわかっているようには感じないのですが、大丈夫でしょうか？

とりあえず、直したらマージして大丈夫です。

2022-06-01 07:18 UTC, minty1202 commented on app/models/todo.rb
> +      tags.delete(Tag.find_by(name: old, user_id:))
これでバグらない？

2022-06-01 07:18 UTC, minty1202 commented on app/models/todo.rb
> +      tags << new_todo_tag  # 末尾に追加
tags << new_todo_tag # 末尾に追加
配列の末尾にたしているだけでこの一行は特に意味をなしていないです

2022-06-01 07:18 UTC, minty1202 commented on spec/models/tag_spec.rb
> +    tag.name = ' '
s * 11
後10文字以内だともいます

2022-06-01 07:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        todo.todo_tags.create(tag_id: tag_piyo.id)
hoge とかはさすがに変えてください

2022-06-01 07:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect(todo.save_tag(['fuga'])).to_not eq todo.tags.pluck(:name)
さっきはそこまで書きませんでしたが、正確にTodoTagが減ることを表すのであればchangeを用いたほうがいいです。

2022-06-01 07:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag3.name.split(','))}.to change(Tag, :count).by(1)
create(:tag, name: 'tag3')
で作られていて、
todo.save_tag(tag3.name.split(','))
を行うことによってタグ数が増えるのは正しい挙動なのでしょうか？

それであれば大丈夫です。

2022-06-01 07:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag3.name.split(','))}.to change(TodoTag, :count).by(1)
tag3.name.split(',')
これややこしいので
[tag3.name]
とかにしてもらえないでしょうか？

元々 , で区切られていることを想定していない文字列に対してsplitする必要があんまりわからないです

2022-06-01 07:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect{todo.save_tag(tag3.name.split(','))}.to change(TodoTag, :count).by(1)
作ってないじゃん！

2022-06-01 07:54 UTC, kazufoot21 commented on app/models/todo.rb
> +      tags << new_todo_tag  # 末尾に追加
tags << new_todo_tag
がないと今Todoが持っているタグの配列（Todo.tag）に追加されないと思うのですがどうでしょう？

2022-06-01 07:54 UTC, kazufoot21 commented on app/models/todo.rb
> +      tags.delete(Tag.find_by(name: old, user_id:))
バグらないと思います...

2022-06-01 08:02 UTC, merged