[update]#20 明日期限の未完了Todoを取得＆通知
minty1202/kensyu pull request #42
Opened 2022-06-12 22:36 UTC by kazufoot21

2022-06-13 01:16 UTC, minty1202 commented on app/models/todo.rb
> +    return unless expired_tomorrow_todos.count != 0
二重否定はわかりづらいのでifにしてもらえると助かります。

2022-06-13 01:16 UTC, minty1202 commented on app/models/todo.rb
> +    todo_title = expired_tomorrow_todos.map(&:title)
pulckが使えるんじゃない？
多分だけど。

2022-06-13 01:16 UTC, minty1202 commented on app/models/todo.rb
> +    expired_tomorrow_todos = Todo.where(limit_date: Time.current.tomorrow).where(status: 'todo')
これって今日から明日の範囲になってる？
なってるなら大丈夫です
この指定だと過去のものも取得しそうな気がする。

2022-06-13 01:16 UTC, minty1202 commented on db/migrate/20220601081322_add_limit_date_and_status_to_todos.rb
> +    add_column :todos, :limit_date, :date, null: false,  default: Time.current
マイグレーションファイル足して行うようにしてください。

すでにdevelopにマージされてるマイグレーションファイルを書き換えてもheroku上は書き換えないので。

2022-06-13 01:30 UTC, kazufoot21 commented on app/models/todo.rb
> +    return unless expired_tomorrow_todos.count != 0
わかりました。lintでひっかかったので、この形に変えましたがifにもどします。

2022-06-13 01:35 UTC, kazufoot21 commented on app/models/todo.rb
> +    expired_tomorrow_todos = Todo.where(limit_date: Time.current.tomorrow).where(status: 'todo')
該当のものが取得出来ているので大丈夫かと思います。

2022-06-14 01:18 UTC, minty1202 requested changes

2022-06-14 01:18 UTC, minty1202 commented on app/models/todo.rb
> +    if expired_tomorrow_todos.count != 0
前回のコード的に以下のようになると思ってたんだけど。
```ruby
return if expired_tomorrow_todos.count.zero?

2022-06-14 01:18 UTC, minty1202 commented on spec/models/todo_spec.rb
> +        expect(Todo.notice_expired_todo).to be_truthy
be_truthyでは正常に動いたかどうかだけで取得できていることの証明にはなってないです。
あと、毎回テストのたびに通知されても困るのでスタブしてください

```ruby
let(:notifier) { double("mock notifier", ping: 'Working as expected')
before do
   allow(Slack::Notifier).to receive(:new).and_return(notifier)
end
expect(Todo.notice_expired_todo).to eq 'Working as expected'

2022-06-14 07:27 UTC, minty1202 commented on spec/models/todo_spec.rb
> +    end
```ruby
it {  expect(Todo.notice_expired_todo).to eq ('Working as expected') }
```
テストとしてbe_turuthyだと早期ターンしたから大丈夫なのか、期待する値が取れて大丈夫なのかわからないのでこれも足してください

2022-06-14 08:04 UTC, merged