[update]#43 終了期日は過去の日付を登録できないようにする
minty1202/kensyu pull request #89
Opened 2022-07-11 05:33 UTC by kazufoot21

# Why
現状どの日付でも登録できてしまうため

# What
新規登録 → 過去の日付は登録できないようにする

更新→ 期日の入力に変化があれば → 過去の日付は登録できないようにする

2022-07-11 08:59 UTC, kazufoot21 commented on spec/models/todo_spec.rb
>    end
この部分で終了期日のバリデーションに引っかかったしまい詰まっています。
過去の日付のものを新しく作成することができなくなるので、
過去に作成したtodoを参照して、それを"未完了から期限切れに変える”という方向で考えたのですが、形にできずにいます。
考え方等のご教授をお願いいたします。

2022-07-11 09:52 UTC, minty1202 commented on spec/models/todo_spec.rb
>    end
https://qiita.com/jagio/items/22cd7be7a052d20c409c
こういうの使えないの？

2022-07-12 01:02 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      end.flatten.uniq
ここは別要件では？

2022-07-12 03:31 UTC, minty1202 requested changes

2022-07-12 03:31 UTC, minty1202 commented on app/models/todo.rb
> +    errors.add(:limit_date, 'は先の日付にしてください') if limit_date.nil? || limit_date < Date.today # or Time.current.yesterday
Time
https://qiita.com/jnchito/items/cae89ee43c30f5d6fa2c

2022-07-13 01:33 UTC, minty1202 approved these changes

2022-07-13 01:35 UTC, merged