[update]#44 バッチ処理 スラックへの通知を1回のみにする
minty1202/kensyu pull request #91
Opened 2022-07-11 09:12 UTC by kazufoot21

# why
例外が発生した際に、スラックへの通知は3回送る必要がないため

 # What
スラックへの通知は1度のみし、失敗した結果のみを通知する

2022-07-11 10:14 UTC, minty1202 commented on lib/tasks/change_status.rake
>      else
```ruby
    else
        puts e
    end
      message = p "期限切れのTodoステータス変更が失敗しました!(#{num_attempts}回目目)"
      Todo.send_error_message(message)
  ensure
```
の方がすっきりすると思うのですが。
いかがですか？

2022-07-11 10:20 UTC, kazufoot21 commented on lib/tasks/change_status.rake
>      else
承知しました。確認してみます。

2022-07-12 00:57 UTC, minty1202 requested changes

2022-07-12 00:57 UTC, minty1202 commented on lib/tasks/change_status.rake
> +      sleep 3
なんで３秒？

2022-07-12 00:57 UTC, minty1202 commented on lib/tasks/todo_notifier.rake
>    end
ここもうそろそろいらないと思うんだよね

2022-07-12 00:57 UTC, minty1202 commented on lib/tasks/todo_notifier.rake
> +    message = p "1日後に終了期限のTodo取得が失敗しました!(#{num_attempts}回目目)"
p は消し忘れ？

2022-07-12 03:28 UTC, minty1202 approved these changes

2022-07-12 03:28 UTC, minty1202 commented on lib/tasks/change_status.rake
> +    if num_attempts < MAX_ATTEMPTS
これだと最大２回な気がするんだけど大丈夫？

2022-07-12 03:34 UTC, kazufoot21 commented on lib/tasks/change_status.rake
> +    if num_attempts < MAX_ATTEMPTS
はい、確認しましたが3回目でスラックに通知来ています。

2022-07-12 03:34 UTC, merged