[update]#41 画像を表示させる ＆ 画像の追加と削除が同時にできるようにする
minty1202/kensyu pull request #92
Opened 2022-07-12 02:49 UTC by kazufoot21

# why
画像がリンク切れになっているため

![スクリーンショット 2022-07-11 6 47 59](https://user-images.githubusercontent.com/73515602/178163222-60409eca-1633-48d4-9d8a-341578a6dc18.png)

画像の追加と削除が同時にできるようにする

# what
エラーページのroutesを一旦コメントアウトにする

画像の保存→選択された画像を削除する流れ
validate :file_length, unless: -> { validation_context == :to_delete_images }を設定

2022-07-12 03:35 UTC, minty1202 reviewed
画像がリンク切れになっているため
これはS3とか構築するかherokuのプランを上げないといけないのでそもそも無理ですね。コードでどうにかできる問題じゃないです。

コード前回とあんまり変わってなさそうだけど、３枚以上追加できちゃうんじゃなかったっけ？

2022-07-12 05:24 UTC, kazufoot21 commented
> コード前回とあんまり変わってなさそうだけど、３枚以上追加できちゃうんじゃなかったっけ？

3枚以上追加できないようにしましたが、3枚以上できてしまう時があるので確認中です

2022-07-12 07:02 UTC, kazufoot21 commented
> > コード前回とあんまり変わってなさそうだけど、３枚以上追加できちゃうんじゃなかったっけ？
> 
> 3枚以上追加できないようにしましたが、3枚以上できてしまう時があるので確認中です

@minty1202 
`return @todo.save unless params[:todo][:image_ids]`
としても先ほどと同じで、１つでも削除対象があれば無限に新しい画像が追加できてしまうのですが、他に考えられる原因があればご教授お願いします

```
    def delete_images
      return @todo.save unless params[:todo][:image_ids]

      @todo.save (context: :to_delete_images) ①
      params[:todo][:image_ids].each do |image_id|
        @todo.images.find(image_id).purge
      end
      @todo.images.reload
      @todo.save
    end
```

`① の@todo.save `のみだと`undefined method purge`になります。
削除のみであれば通常にできますが、追加と削除だとimageの型がEnumratorになりそれが原因だと考えます。

2022-07-12 07:10 UTC, minty1202 commented
じゃあ場当たり的な修正は難しそうなので
tag_todo_valid?
あたりからきれいに整理することから始めたほうがいいですね。

2022-07-14 08:42 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    end
これだと画像が多い的なエラーなくない？

2022-07-14 08:42 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      if tag_todo_valid?(new_tag, @todo)
imgもはじいてるのにこの名前はおかしい

2022-07-14 08:58 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +    end
@minty1202 
`new_and_old_images_ids <= 3 && @todo.valid?` のように@todo.valid?を画像と一緒にやろうとすると3枚以上ある状態から同時に追加と削除ができなるなるのですが、なにか方法がありますでしょうか。最低限の代わりとしては”更新に失敗しました”を追加しています。

2022-07-14 09:08 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    end
@tags_errorsみたいなことをすればいいのではないのでしょうか？

2022-07-15 01:12 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +    end
@minty1202 
@todo.imagesが有効（3枚以上でない）で、エラーメッセージが持っていないかということを確認すればいいのでしょうか？→この場合3枚以上持っている状態から新しく追加ができなくなりそうな気がしますが、いかかでしょう。

@tags_errorsみたいなとういと、下記のような感じでしょうか？ （image単体でなくimages全体で見ないといけないので違いますよね、、）
```
      @image_errors = @todo.images.map do |image|
        todo = Todo.new(title: @todo.title, text: @todo.text, limit_date: @todo.limit_date, status: @todo.status, images: image)
        todo.valid?
        todo.errors.full_messages
      end.flatten.uniq

      new_and_old_images_ids <= 3 && @image_errors.errors.empty?
```

2022-07-15 01:17 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    end
前提として@tags_errorsが表示されているロジックってわかってますか？

2022-07-15 01:23 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +    end
@minty1202 
配列で送られてきた複数のタグを1つずつ取り出して、バリデーションにかけている ということだと思います。

2022-07-15 01:33 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +    end
@kazufoot21 
そうではなく、なぜひょうじできているかです

2022-07-15 01:48 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +    end
@minty1202 
すみません、わからないので教えて下さい

2022-07-15 07:21 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
```
     Failure/Error: add_images = params[:todo][:images] ? params[:todo][:images].count : 0
     
     ArgumentError:
       wrong number of arguments (given 0, expected 1+)

rspec ./spec/requests/user/todos_spec.rb:67 # Todos POST users/todos #create ログインしている場合 登録が成功する場合 画像投稿がある場合 登録されること(画像あり)
```

ここの部分のテストが引っかかるのですが、どの部分の引数をいっているのでしょうか？

2022-07-15 07:57 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
さすがにわからん。
すまん。
多分params[:todo]すらそんざいしないんじゃない？

2022-07-15 08:32 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
params[:todo]の条件分岐試してみましたが結果は変わりませんでした。
`params[:todo][:images].count`の部分が問題ありそうな気もしています、、。

2022-07-19 01:33 UTC, minty1202 requested changes

2022-07-19 01:33 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      @image_error = '3枚以上画像は登録できません'
先にメッセージを入れるはおかしい

2022-07-19 01:33 UTC, minty1202 commented on app/views/users/todos/_form.html.slim
> +      - if @todo.images.count > 3
@todo.images.count > 3
そもそも画像３枚以上で表示させるはずだからこここれが必要ならばコントローラーがおかしい

2022-07-19 03:11 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      end
```ruby
@image_error = '3枚以上画像は登録できません' if new_and_old_images_ids <= 3
```
で事足りそうなのですが。

2022-07-19 03:11 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      add_images = params.dig(:todo, :images) ? params.dig(:todo, :images)&.count : 0
params.dig(:todo, :images)&.count
ぼっち演算子にする必要があるんですか？

2022-07-19 03:11 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
こんなに複雑に計算しなくてもいけると思うんだけど。
```ruby
@todo.images.count - params.dig(:todo, :image_ids).to_a.count
```
だとダメなの？

2022-07-19 03:28 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
@todo.images.count が 今ある画像と追加した画像の合計になるので、params[:todo][:images].to_a.count で追加した画像も引く必要があります。

2022-07-19 03:29 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      end
上記試しましtが、エラー文言が表示されなくなります

2022-07-19 03:29 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      add_images = params.dig(:todo, :images) ? params.dig(:todo, :images)&.count : 0
試したところぼっち演算子なしでも大丈夫そうです

2022-07-19 03:34 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
>今ある画像と追加した画像の合計になる

であれば
残った数 + 追加数 = 合計数
という計算を挟む必要がない気がするんですが、いかがですか？

2022-07-19 03:37 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      end
@image_error = '3枚以上画像は登録できません' unless new_and_old_images_ids <= 3

2022-07-19 03:54 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
この部分の合計数というのは、削除する画像を除いたものになるので必要かと思います。 
全体（既存数＋追加数）は削除する画像も含んでいます。

2022-07-19 03:58 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      end
そちらも事前に試しましたが、3枚以上登録できるようになります
```
 return if new_and_old_images_ids <= 3
3枚以上画像は登録できません' 
return false 
```
なども試してみましたが、期待通り動かなかったので現在の形で書いています

2022-07-19 04:19 UTC, minty1202 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
私が聞きたいのは
`params[:todo][:images].to_a.count`と`params.dig(:todo, :images)`これってほぼ同じ意味なのになんで一回引いてからまた足してるのか？ってことなんです。

```rb
      # 全体（既存数＋追加数） - 削除数 - 追加数  = 残った数
      left_images_ids = @todo.images.count - params.dig(:todo, :image_ids).to_a.count - params[:todo][:images].to_a.count
      add_images = params.dig(:todo, :images) ? params.dig(:todo, :images).count : 0
      # 残った数 + 追加数 = 合計数
      new_and_old_images_ids = left_images_ids + add_images
```
これを日本語にしたとき

```ruby
@todo.images.count = '全体数（既存数＋追加数）'
params.dig(:todo, :image_ids).to_a.count = '消したい画像の個数'
params[:todo][:images].to_a.count = '新しく追加される画像数'
params.dig(:todo, :images) ? params.dig(:todo, :images).count : 0 = '新しく追加される画像数または0'
↓
残った数 = 全体数（既存数＋追加数） - 消したい画像の個数 - 新しく追加されている画像の個数
new_and_old_images_ids = 残った数 + 新しく追加される画像数または0
```

という計算をする理由がわからないので、申し訳ないのですが、改めて教えていただけませんか?

2022-07-19 05:03 UTC, kazufoot21 commented on app/controllers/users/todos_controller.rb
> +      new_and_old_images_ids = left_images_ids + add_images
改めて考えてみましたら、
 left_images_ids = @todo.images.count - params.dig(:todo, :image_ids).to_a.count
のみで大丈夫そうです。ご指摘ありがとうございます

2022-07-19 06:26 UTC, minty1202 approved these changes

2022-07-19 08:10 UTC, merged